-- MySQL Script generated by MySQL Workbench
-- Fri Mar 17 14:36:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema uninorthwest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uninorthwest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uninorthwest` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `uninorthwest` ;

-- -----------------------------------------------------
-- Table `uninorthwest`.`semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uninorthwest`.`semester` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `SemesterName` VARCHAR(255) NOT NULL,
  `SemesterYear` INT NULL DEFAULT NULL,
  `Inprogress` TINYINT NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uninorthwest`.`tutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uninorthwest`.`tutor` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `CreationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uninorthwest`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uninorthwest`.`modules` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `ModuleName` VARCHAR(255) NOT NULL,
  `TutorId` INT NULL DEFAULT NULL,
  `SemesterId` INT NOT NULL,
  `CreationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `modules_sem_idx` (`SemesterId` ASC) VISIBLE,
  INDEX `module_fk_tutor` (`TutorId` ASC) VISIBLE,
  CONSTRAINT `module_fk_sem`
    FOREIGN KEY (`SemesterId`)
    REFERENCES `uninorthwest`.`semester` (`Id`),
  CONSTRAINT `module_fk_tutor`
    FOREIGN KEY (`TutorId`)
    REFERENCES `uninorthwest`.`tutor` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uninorthwest`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uninorthwest`.`students` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Gender` ENUM('M', 'F', 'O') NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Phone` VARCHAR(45) NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uninorthwest`.`studentattendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uninorthwest`.`studentattendance` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `StudentId` INT NULL DEFAULT NULL,
  `ModuleId` INT NULL DEFAULT NULL,
  `IsCheckedIn` TINYINT(1) NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `StudentId` (`StudentId` ASC) VISIBLE,
  INDEX `ModuleId` (`ModuleId` ASC) VISIBLE,
  CONSTRAINT `studentattendance_ibfk_1`
    FOREIGN KEY (`StudentId`)
    REFERENCES `uninorthwest`.`students` (`Id`),
  CONSTRAINT `studentattendance_ibfk_2`
    FOREIGN KEY (`ModuleId`)
    REFERENCES `uninorthwest`.`modules` (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `uninorthwest`.`studentcheck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uninorthwest`.`studentcheck` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `StudentId` INT NULL DEFAULT NULL,
  `ModuleId` INT NULL DEFAULT NULL,
  `CreationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  INDEX `StudentId` (`StudentId` ASC) VISIBLE,
  INDEX `ModuleId` (`ModuleId` ASC) VISIBLE,
  CONSTRAINT `studentcheck_ibfk_1`
    FOREIGN KEY (`StudentId`)
    REFERENCES `uninorthwest`.`students` (`Id`),
  CONSTRAINT `studentcheck_ibfk_2`
    FOREIGN KEY (`ModuleId`)
    REFERENCES `uninorthwest`.`modules` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
